name: base
channels:
  - conda-forge
  - pytorch
  - dglteam
  - rdkit
dependencies:
  - conda-forge::pip=22.3
  - conda-forge::numpy=1.20
  - conda-forge::pandas=1.3.5
  - conda-forge::cudatoolkit=11.3
  - pytorch::pytorch=1.12.1=py3.7_cuda11.3_cudnn8.3.2_0
  - pytorch::torchvision=0.13.1
  - dglteam::dgl-cuda11.3
  - rdkit::rdkit=2020.09.1.0
  - pip:
      - tensorboardx==2.5.1
